services:
  db:
    image: postgres:15
    container_name: postgres_sistema
    environment:
      POSTGRES_USER: postgres      # ← MUDAR para 'postgres'
      POSTGRES_PASSWORD: 123456    # ← MUDAR para '123456'
      POSTGRES_DB: sistema_vendas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: